services:
  mysql:
    image: mysql:8.0
    container_name: lab-supervise-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datn
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    image: bachld2612/lab-supervise-backend:1.0.0-20260515
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: lab-supervise-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/datn?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT: ${JWT}
      APP_RSA_PRIVATE_KEY: ${APP_RSA_PRIVATE_KEY:-}
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql_data:
